### ISSUE TITLE
Add support for sub-directory

### ISSUE THREAD

**Issue by dedupely** [okkyhtf/aurora-alpine#1]
I have this set up on a sub directory and it seems sending me to my main domain. Clicking on the logo, selecting a server uses my domain.com/ as root instead of using the domain.com/bsa/

**Comment by okkyhtf** [comment]
I'm not really sure what you were referring to, can you elaborate more on this?

**Comment by dedupely** [comment]
Ok, so let's say I have the dashboard pointing (proxied) to mydomain.com/beans-admin

There are a few links that don't appear to use the `mydomain.com/beans-admin` path as root, but rather `mydomain.com` which causes broken links.

**Comment by okkyhtf** [comment]
This repo only wraps the aurora project inside a Docker container. So I think you need to address this issue to https://github.com/xuri/aurora instead?

**Comment by dedupely** [comment]
You're right. I'll take it up with them.
